# config/packages/fos_user.yaml

fos_user:
  db_driver: orm
  firewall_name: main
  user_class: App\Entity\User
  registration:
    confirmation:
      enabled: false
  from_email:
    address: '%env(MAILER_USER_ADDRESS)%'
    sender_name: '%env(MAILER_USER_NAME)%'
  service:
    user_manager: sonata.user.orm.user_manager
    mailer: 'fos_user.mailer.noop'
  group:
    group_class:   FOS\UserBundle\Entity\Group
    group_manager: sonata.user.orm.group_manager