sonata_admin:
    title: 'Sonata Admin'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
    security:
        handler: sonata.admin.security.handler.acl
    options:
        form_type: 'horizontal'
