
parameters:
    locale: en
    activated_locales: ['%locale%','fr','ru','pl']
    locales_requirements: '%locale%|fr|ru|pl'

services:
    security.acl.permission.map:
        class: Sonata\AdminBundle\Security\Acl\Permission\AdminPermissionMap

    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    forms:
        namespace: App\Form\
        resource: '../src/Form'

    App\Admin\PostAdmin:
        arguments: [~, App\Entity\Post, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Post }

    App\Admin\CategoryAdmin:
        arguments: [~, App\Entity\Category, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Category }

    App\Admin\AvatarImageAdmin:
        arguments: [~, App\Entity\ImageAvatar, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: ImageAvatar }

    App\Admin\PostImagesAdmin:
        arguments: [~, App\Entity\PostImages, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: PostImages }

    App\Admin\StaffAvatarAdmin:
        arguments: [~, App\Entity\StaffAvatar, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: StaffAvatar }

    App\Admin\ContactInformationAdmin:
        arguments: [~, App\Entity\ContactInformation, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: ContactInformation }

    App\Admin\StaffAdmin:
        arguments: [~, App\Entity\Staff, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: StaffAdmin }

    App\Admin\CustomerAvatarAdmin:
        arguments: [~, App\Entity\CustomerAvatar, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: CustomerAvatar }

    App\Admin\CustomerReviewAdmin:
        arguments: [~, App\Entity\CustomerReview, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: CustomerReview }

    App\Admin\LocationAdmin:
        arguments: [~, App\Entity\Location, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Location }

    App\Repository\CategoryRepository:
    App\Repository\PostRepository:
    App\Repository\AvatarImageRepository:
    App\Repository\PostImagesRepository:
    App\Repository\StaffAvatarRepository:
    App\Repository\ContactInformationRepository:
    App\Repository\StaffRepository:
    App\Repository\CustomerAvatarRepository:
    App\Repository\CustomerReviewRepository:
    App\Repository\LocationRepository:

    App\Service\ContactInfoService:
    App\Service\SearchService:

    mailer:
        alias: fos_user.mailer.noop
        public: true