
parameters:

services:
    security.acl.permission.map:
        class: Sonata\AdminBundle\Security\Acl\Permission\AdminPermissionMap


    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.


    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'


    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']


    App\Admin\PostAdmin:
        arguments: [~, App\Entity\Post, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Post }

    App\Admin\CategoryAdmin:
        arguments: [~, App\Entity\Category, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Category }

    App\Repository\CategoryRepository:
    App\Repository\PostRepository:

    mailer:
        alias: fos_user.mailer.noop
        public: true